Make bootstrap complain about missing dependencies on Ubuntu/Debian.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,5 +1,24 @@
 #!/bin/sh
 set -e
+
+if command -v lsb_release >/dev/null 2>&1; then
+    case "$(lsb_release --id --short)" in
+	Ubuntu|Debian)
+	    for package in python-virtualenv python-dev libxml2-dev libxslt1-dev python-libvirt; do
+		if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+                    # add a space after old values
+		    missing="${missing:+$missing }$package"
+		fi
+	    done
+	    if [ -n "$missing" ]; then
+		echo "$0: missing required packages, please install them:" 1>&2
+		echo "  sudo apt-get install $missing"
+		exit 1
+	    fi
+	    ;;
+    esac
+fi
+
 # site packages needed because libvirt python bindings are not nicely
 # packaged
 test -d virtualenv || virtualenv --system-site-packages --distribute virtualenv
